import Head from 'next/head'

export default function Home() {
  return (
    <section>
      <Head>
        <title>Crud Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='text-xl md:'>
          Employee Management
        </h1>
      </main>
    </section>
  )
}
