import Head from 'next/head';
import { BiUserPlus } from 'react-icons/bi';
import Form from './components/form';
import Table from './components/table';

export default function Home() {
  return (
    <section>
      <Head>
        <title>Crud Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>
          Employee Management
        </h1>

        <div className='container mx-auto flex justify-between py-5 border-b'>
          <div className='left flex gap-3'>
            <button className='flex bg-indigo-500 text-white px-3 py-3 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800'>
              Add Employee
              <span className='pl-2'><BiUserPlus size={23} /></span> 
            </button>
          </div>
        </div>

        {/* collapsable form */}
        <div className='container mx-auto py-5'>
          <Form />
        </div>

        {/* Table */}
        <div className='container mx-auto'>
          <Table />
        </div>
      </main>
    </section>
  )
}
